spring.application.name=com.venta.repuestos

# Configuracion de la base de datos
server.port=8010
spring.datasource.url=jdbc:mysql://localhost:3306/bd_venta_repuestos
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name = com.mysql.cj.jdbc.Driver

##server.port=8081
#Jpa y Hibernate configuration
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#SpringSecurity
security.jwt.key.private=8716a7626531e2d445f17c60524c5e83bbd33698ea8b42e433f981b063f52bf8
security.jwt.user.generator=AUTH0JWT-BACKEND